language: c
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - opam
install:
  - opam init --yes
  - opam update --yes
  - opam switch --yes $OCAML_VERSION
  - eval `opam config env`
  - opam switch
  - opam install --yes ounit core
  - opam upgrade --yes
  - opam list
script:
  - corebuild -use-ocamlfind unit_tests.byte
  - _build/unit_tests.byte
env:
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.05.0
cache:
  directories:
  - $HOME/.opam
