language: c
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - aspcud
install:
  - wget --output-document=$HOME/opam2 https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux
  - chmod +x $HOME/opam2
  - test -d $HOME/.opam/$OCAML_VERSION || $HOME/opam2 init --yes --disable-sandboxing --compiler=$OCAML_VERSION
  - $HOME/opam2 update --yes
  - eval `$HOME/opam2 config env`
  - $HOME/opam2 switch list
  - $HOME/opam2 install --yes General$GENERAL_VERSION dune$DUNE_VERSION
  - if $UPGRADE_OPAM; then $HOME/opam2 upgrade --yes; fi
  - $HOME/opam2 list
script:
  - dune runtest
env:
  - OCAML_VERSION=4.02.3 GENERAL_VERSION=.0.6.0 DUNE_VERSION=.1.0.1 UPGRADE_OPAM=false
  - OCAML_VERSION=4.07.1 UPGRADE_OPAM=true
  - OCAML_VERSION=4.07.1+flambda UPGRADE_OPAM=true
cache:
  directories:
  - $HOME/.opam
